### ISSUE TITLE
http api 请求 reranker 模型报错

### ISSUE THREAD

**Issue by ehlxr** [shell-nlp/gpt_server#10]
请求：
```
POST http://10.0.80.31:8082/v1/embeddings
#Authorization: Bearer EMPTY
Content-Type: application/json

{
  "model": "bce-reranker-base_v1",
  "input": [
    "你是谁",
    "今年几岁",
    "你多大了"
  ],
  "extra_json": {
    "query": "你多大了"
  }
}
```
响应：
```
HTTP/1.1 400 Bad Request
date: Mon, 01 Jul 2024 08:37:55 GMT
server: uvicorn
content-length: 65
content-type: application/json

{
  "object": "error",
  "message": "Internal Server Error",
  "code": 50001
}
```

服务错误堆栈：

```
2024-07-01 08:41:47.905 | INFO     | __main__:get_embeddings:58 - params {'model': 'bce-reranker-base_v1', 'input': ['你是谁', '今年几岁', '你多大了'], 'encoding_format': None, 'query': None}
2024-07-01 08:41:47.905 | INFO     | __main__:get_embeddings:59 - worker_id: 4f496ce6
Batches:   0%|                                                                                                                                                                                 | 0/1 [00:00<?, ?it/s]
Batches:   0%|                                                                                                                                                                                 | 0/1 [00:00<?, ?it/s]
2024-07-01 08:41:47 | ERROR | stderr |
INFO:     127.0.0.1:58486 - "POST /worker_get_embeddings HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/model_worker/base.py", line 293, in api_get_embeddings
    embedding = await worker.get_embeddings(params)
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/model_worker/embedding.py", line 75, in get_embeddings
    scores = self.client.predict(sentence_pairs)
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 338, in predict
    for features in iterator:
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 138, in smart_batching_collate_text_only
    texts[idx].append(text.strip())
AttributeError: 'NoneType' object has no attribute 'strip'
2024-07-01 08:41:47 | INFO | stdout | INFO:     10.0.12.165:54154 - "POST /v1/embeddings HTTP/1.1" 400 Bad Request

```

使用 python 示例请求没问题：
```python
from openai import OpenAI

# 新版本 opnai
client = OpenAI(api_key="EMPTY", base_url="http://10.0.80.31:8082/v1")
data = client.embeddings.create(
    model="bce-reranker-base_v1",
    input=["你是谁", "今年几岁", "你多大了"],
    extra_body={"query": "你多大了"},
)

print(data.data)
```

**Comment by shell-nlp** [comment]
> {
>   "model": "bce-reranker-base_v1",
>   "input": [
>     "你是谁",
>     "今年几岁",
>     "你多大了"
>   ],
>   "extra_json": {
>     "query": "你多大了"
>   }
> }

请求体错误修改为：
```
{
  "model": "bce-reranker-base_v1",
  "input": [
    "你是谁",
    "今年几岁",
    "你多大了"
  ],
  "query": "你多大了"
}
```

**Comment by shell-nlp** [comment]
from openai import OpenAI

# 新版本 opnai
client = OpenAI(api_key="EMPTY", base_url="http://10.0.80.31:8082/v1")
data = client.embeddings.create(
    model="bce-reranker-base_v1",
    input=["你是谁", "今年几岁", "你多大了"],
    extra_body={"query": "你多大了"},
)

print(data.data)
extra_body 是openai需要传入额外参数时的处理方式，并不是表示 入参是extra_body

**Comment by shell-nlp** [comment]
> 请求：
> 
> ```
> POST http://10.0.80.31:8082/v1/embeddings
> #Authorization: Bearer EMPTY
> Content-Type: application/json
> 
> {
>   "model": "bce-reranker-base_v1",
>   "input": [
>     "你是谁",
>     "今年几岁",
>     "你多大了"
>   ],
>   "extra_json": {
>     "query": "你多大了"
>   }
> }
> ```
> 
> 响应：
> 
> ```
> HTTP/1.1 400 Bad Request
> date: Mon, 01 Jul 2024 08:37:55 GMT
> server: uvicorn
> content-length: 65
> content-type: application/json
> 
> {
>   "object": "error",
>   "message": "Internal Server Error",
>   "code": 50001
> }
> ```
> 
> 服务错误堆栈：
> 
> ```
> 2024-07-01 08:41:47.905 | INFO     | __main__:get_embeddings:58 - params {'model': 'bce-reranker-base_v1', 'input': ['你是谁', '今年几岁', '你多大了'], 'encoding_format': None, 'query': None}
> 2024-07-01 08:41:47.905 | INFO     | __main__:get_embeddings:59 - worker_id: 4f496ce6
> Batches:   0%|                                                                                                                                                                                 | 0/1 [00:00<?, ?it/s]
> Batches:   0%|                                                                                                                                                                                 | 0/1 [00:00<?, ?it/s]
> 2024-07-01 08:41:47 | ERROR | stderr |
> INFO:     127.0.0.1:58486 - "POST /worker_get_embeddings HTTP/1.1" 500 Internal Server Error
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
>     return await self.app(scope, receive, send)
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
>     await super().__call__(scope, receive, send)
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
>     raise exc
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
>     await self.app(scope, receive, _send)
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
>     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
>     raise exc
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
>     await app(scope, receive, sender)
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
>     await route.handle(scope, receive, send)
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
>     await self.app(scope, receive, send)
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
>     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
>     raise exc
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
>     await app(scope, receive, sender)
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
>     response = await func(request)
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
>     raw_response = await run_endpoint_function(
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
>     return await dependant.call(**values)
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/model_worker/base.py", line 293, in api_get_embeddings
>     embedding = await worker.get_embeddings(params)
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/model_worker/embedding.py", line 75, in get_embeddings
>     scores = self.client.predict(sentence_pairs)
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 338, in predict
>     for features in iterator:
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
>     for obj in iterable:
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
>     data = self._next_data()
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
>     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
>     return self.collate_fn(data)
>   File "/home/ubuntu/lxr/gpt_server-main/gpt_server/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 138, in smart_batching_collate_text_only
>     texts[idx].append(text.strip())
> AttributeError: 'NoneType' object has no attribute 'strip'
> 2024-07-01 08:41:47 | INFO | stdout | INFO:     10.0.12.165:54154 - "POST /v1/embeddings HTTP/1.1" 400 Bad Request
> ```
> 
> 使用 python 示例请求没问题：
> 
> ```python
> from openai import OpenAI
> 
> # 新版本 opnai
> client = OpenAI(api_key="EMPTY", base_url="http://10.0.80.31:8082/v1")
> data = client.embeddings.create(
>     model="bce-reranker-base_v1",
>     input=["你是谁", "今年几岁", "你多大了"],
>     extra_body={"query": "你多大了"},
> )
> 
> print(data.data)
> ```

如果问题已解决。请关闭issue
