### ISSUE TITLE
部署minicpm-v-2.6模型推理报错

### ISSUE THREAD

**Issue by sph116** [shell-nlp/gpt_server#20]
minicpm-v-2.6模型推理报错 报错后 进程直接挂掉

**环境** 
官方docker镜像
docker.rainbond.cc/506610466/gpt_server:latest 
**配置文件**

```
serve_args:
  host: 0.0.0.0
  port: 8082
  controller_address: http://localhost:21001
  api_keys: null
controller_args:
  host: 0.0.0.0
  port: 21001
  dispatch_method: shortest_queue
model_worker_args:
  host: 0.0.0.0
  controller_address: http://localhost:21001
models:
- MiniCPM-V-2_6:
    alias: MiniCPM-V-2_6
    enable: true
    model_name_or_path: /workdir/rag_doc_parser/models/MiniCPM-V-2_6
    model_type: minicpmv
    work_mode: lmdeploy-turbomind
    device: gpu
    workers:
    - gpus:
      - 1
      - 2
      - 3
      - 4
```

**推理代码**

```
client = OpenAI(api_key="EMPTY", base_url="http://192.168.2.153:8082/v1")
stream = True
output = client.chat.completions.create(
    model="MiniCPM-V-2_6",  # internlm chatglm3  qwen  llama3 chatglm4
    messages=[
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "请描述这个图片",
                },
                {
                    "type": "image_url",
                    "image_url": {
                        "url": "https://opencompass.oss-cn-shanghai.aliyuncs.com/image/compass-hub/botchat_banner.png",
                    },
                },
            ],
        }
    ],
    stream=stream,
)
if stream:
    for chunk in output:
        print(chunk.choices[0].delta.content or "", end="", flush=True)
else:
    print(output.choices[0].message.content)
print()
```

**报错信息**

024-10-25 01:26:03,570 - lmdeploy - INFO - prompt='<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n<image_id>0</image_id><image><IMAGE_TOKEN></image><slice><IMAGE_TOKEN></slice><slice><IMAGE_TOKEN></slice><slice><IMAGE_TOKEN></slice><slice><IMAGE_TOKEN></slice><slice><IMAGE_TOKEN></slice><slice><IMAGE_TOKEN></slice><slice><IMAGE_TOKEN></slice><slice><IMAGE_TOKEN></slice>\n请描述这个图片<|im_end|>\n<|im_start|>assistant\n', gen_config=GenerationConfig(n=1, max_new_tokens=4096, do_sample=True, top_p=1.0, top_k=50, min_p=0.0, temperature=0.7, repetition_penalty=1.0, ignore_eos=False, random_seed=3879820818716201380, stop_words=['<|im_end|>', '<|endoftext|>'], bad_words=None, stop_token_ids=[151643, 151645], bad_token_ids=None, min_new_tokens=None, skip_special_tokens=True, logprobs=None, response_format=None, logits_processors=None), prompt_token_id=[151644, 8948, 198, 2610, 525, 264, 10950, 17847, 13, 151645, 198, 151644, 872, 198, 151658, 15, 151659, 151646, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151647, 151656, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151657, 151656, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151657, 151656, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151657, 151656, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151657, 151656, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151657, 151656, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151657, 151656, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151657, 151656, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 151657, 198, 14880, 53481, 99487, 45930, 151645, 198, 151644, 77091, 198], adapter_name=None.
2024-10-25 01:26:03,570 - lmdeploy - INFO - session_id=1, history_tokens=0, input_tokens=621, max_new_tokens=4096, seq_start=True, seq_end=True, step=0, prep=True
2024-10-25 01:26:03,570 - lmdeploy - INFO - Register stream callback for 1
[TM][INFO] [forward] Enqueue requests
[TM][INFO] [forward] Wait for requests to complete ...
[TM][INFO] [ProcessInferRequests] Request for 1 received.
[TM][INFO] ------------------------- step = 620 -------------------------
[TM][INFO] [Forward] [0, 1), dc=0, pf=1, sum_q=621, sum_k=621, max_q=621, max_k=621
terminate called after throwing an instance of 'std::runtime_error'
  what():  [TM][ERROR]  Assertion fail: /lmdeploy/src/turbomind/kernels/attention/attention.cu:35 

2024-10-25 01:26:04 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-10-25 01:26:04 | ERROR | stderr | Traceback (most recent call last):
2024-10-25 01:26:04 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 257, in __call__
2024-10-25 01:26:04 | ERROR | stderr |     await wrap(partial(self.listen_for_disconnect, receive))
2024-10-25 01:26:04 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 253, in wrap
2024-10-25 01:26:04 | ERROR | stderr |     await func()
2024-10-25 01:26:04 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 230, in listen_for_disconnect
2024-10-25 01:26:04 | ERROR | stderr |     message = await receive()
2024-10-25 01:26:04 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 587, in receive
2024-10-25 01:26:04 | ERROR | stderr |     await self.message_event.wait()
2024-10-25 01:26:04 | ERROR | stderr |   File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
2024-10-25 01:26:04 | ERROR | stderr |     await fut
2024-10-25 01:26:04 | ERROR | stderr | asyncio.exceptions.CancelledError: Cancelled by cancel scope 72259b2635b0
2024-10-25 01:26:04 | ERROR | stderr | 
2024-10-25 01:26:04 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-10-25 01:26:04 | ERROR | stderr | 
2024-10-25 01:26:04 | ERROR | stderr |   + Exception Group Traceback (most recent call last):
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2024-10-25 01:26:04 | ERROR | stderr |   |     result = await app(  # type: ignore[func-returns-value]
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-10-25 01:26:04 | ERROR | stderr |   |     return await self.app(scope, receive, send)
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
2024-10-25 01:26:04 | ERROR | stderr |   |     await super().__call__(scope, receive, send)
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 113, in __call__
2024-10-25 01:26:04 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 187, in __call__
2024-10-25 01:26:04 | ERROR | stderr |   |     raise exc
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 165, in __call__
2024-10-25 01:26:04 | ERROR | stderr |   |     await self.app(scope, receive, _send)
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 85, in __call__
2024-10-25 01:26:04 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-10-25 01:26:04 | ERROR | stderr |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 62, in wrapped_app
2024-10-25 01:26:04 | ERROR | stderr |   |     raise exc
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 51, in wrapped_app
2024-10-25 01:26:04 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 715, in __call__
2024-10-25 01:26:04 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 735, in app
2024-10-25 01:26:04 | ERROR | stderr |   |     await route.handle(scope, receive, send)
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 288, in handle
2024-10-25 01:26:04 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 76, in app
2024-10-25 01:26:04 | ERROR | stderr |   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 62, in wrapped_app
2024-10-25 01:26:04 | ERROR | stderr |   |     raise exc
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 51, in wrapped_app
2024-10-25 01:26:04 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 74, in app
2024-10-25 01:26:04 | ERROR | stderr |   |     await response(scope, receive, send)
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 250, in __call__
2024-10-25 01:26:04 | ERROR | stderr |   |     async with anyio.create_task_group() as task_group:
2024-10-25 01:26:04 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 763, in __aexit__
2024-10-25 01:26:04 | ERROR | stderr |   |     raise BaseExceptionGroup(
2024-10-25 01:26:04 | ERROR | stderr |   | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
2024-10-25 01:26:04 | ERROR | stderr |   +-+---------------- 1 ----------------
2024-10-25 01:26:04 | ERROR | stderr |     | Traceback (most recent call last):
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
2024-10-25 01:26:04 | ERROR | stderr |     |     yield
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 257, in __aiter__
2024-10-25 01:26:04 | ERROR | stderr |     |     async for part in self._httpcore_stream:
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/connection_pool.py", line 367, in __aiter__
2024-10-25 01:26:04 | ERROR | stderr |     |     raise exc from None
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/connection_pool.py", line 363, in __aiter__
2024-10-25 01:26:04 | ERROR | stderr |     |     async for part in self._stream:
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/http11.py", line 349, in __aiter__
2024-10-25 01:26:04 | ERROR | stderr |     |     raise exc
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/http11.py", line 341, in __aiter__
2024-10-25 01:26:04 | ERROR | stderr |     |     async for chunk in self._connection._receive_response_body(**kwargs):
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/http11.py", line 210, in _receive_response_body
2024-10-25 01:26:04 | ERROR | stderr |     |     event = await self._receive_event(timeout=timeout)
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_async/http11.py", line 220, in _receive_event
2024-10-25 01:26:04 | ERROR | stderr |     |     with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
2024-10-25 01:26:04 | ERROR | stderr |     |     self.gen.throw(typ, value, traceback)
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2024-10-25 01:26:04 | ERROR | stderr |     |     raise to_exc(exc) from exc
2024-10-25 01:26:04 | ERROR | stderr |     | httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2024-10-25 01:26:04 | ERROR | stderr |     |
2024-10-25 01:26:04 | ERROR | stderr |     | The above exception was the direct cause of the following exception:
2024-10-25 01:26:04 | ERROR | stderr |     |
2024-10-25 01:26:04 | ERROR | stderr |     | Traceback (most recent call last):
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 253, in wrap
2024-10-25 01:26:04 | ERROR | stderr |     |     await func()
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 242, in stream_response
2024-10-25 01:26:04 | ERROR | stderr |     |     async for chunk in self.body_iterator:
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/workdir/gpt_server/gpt_server/serving/openai_api_server.py", line 492, in chat_completion_stream_generator
2024-10-25 01:26:04 | ERROR | stderr |     |     async for content in generate_completion_stream(gen_params, worker_addr):
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/workdir/gpt_server/gpt_server/serving/openai_api_server.py", line 684, in generate_completion_stream
2024-10-25 01:26:04 | ERROR | stderr |     |     async for raw_chunk in response.aiter_raw():
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/dist-packages/httpx/_models.py", line 989, in aiter_raw
2024-10-25 01:26:04 | ERROR | stderr |     |     async for raw_stream_bytes in self.stream:
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 150, in __aiter__
2024-10-25 01:26:04 | ERROR | stderr |     |     async for chunk in self._stream:
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 256, in __aiter__
2024-10-25 01:26:04 | ERROR | stderr |     |     with map_httpcore_exceptions():
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
2024-10-25 01:26:04 | ERROR | stderr |     |     self.gen.throw(typ, value, traceback)
2024-10-25 01:26:04 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
2024-10-25 01:26:04 | ERROR | stderr |     |     raise mapped_exc(message) from exc
2024-10-25 01:26:04 | ERROR | stderr |     | httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2024-10-25 01:26:04 | ERROR | stderr |     +------------------------------------
Aborted (core dumped)

**Comment by shell-nlp** [comment]
我测试了一下， 并没有报错， 而且 vllm 后端也已经支持了， 你试一下 vllm 后端

**Comment by shell-nlp** [comment]
![image](https://github.com/user-attachments/assets/e57e90c3-fbe4-40fa-9e74-6f3515ad7c36)
欢迎加入交流下，可以更方便为你解决问题

**Comment by sph116** [comment]
问题已解决 
不支持bf16的gpu 需要于https://github.com/shell-nlp/gpt_server/tree/main/gpt_server/model_backend 指定推理引擎的dtype
